### ISSUE TITLE
Issue with single elimination as main event

### ISSUE THREAD

**Issue by botagas** [kostrykin/tournaments#13]
Hello,

There is an issue with knockout when used with uneven amount of players (3-5-7 and probably many other variants).
```
stages:
- id: main_round
  name: Elimination
  mode: knockout

podium:
- main_round.placements[:3]
```

The webUI gives us the following error:
`Error while initializing tournament (Negative indexing is not supported.).`

This isn't very informative to the user. Could be improved. At least if there was a possibility for the user to set up byes, or have the system resort to automatic byes on its own (or if it was possible to define in YAML format to enable automatic-byes for player amounts that are not a power of two), that would be great.
